name: CodeGuru Security Example
on:  
  push:
    branches:
      - 'main'
      - 'codeguru'
  pull_request:
    branches:
      - 'main'
      - 'codeguru'

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::904233125795:role/acme-admin
          aws-region: eu-north-1
          role-session-name: GitHubActionScript

      - name: Get OIDC Token
        id: get_token
        uses: actions/github-script@v6
        with:
          script: |
            const id_token = await core.getIDToken('sts.amazonaws.com');
            core.setOutput('id_token', id_token);

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract 'sub' Claim from OIDC Token
        run: |
          echo "Extracting 'sub' claim from OIDC token..."
          OIDC_TOKEN="${{ steps.get_token.outputs.id_token }}"
          if [ -z "$OIDC_TOKEN" ]; then
            echo "OIDC token not available."
            exit 1
          fi
          PAYLOAD=$(echo "${OIDC_TOKEN}" | cut -d '.' -f2)
          # Replace base64url characters with base64 characters
          PAYLOAD=$(echo "${PAYLOAD}" | tr '_-' '/+')
          # Add necessary padding
          PADDING=$(( (4 - ${#PAYLOAD} % 4) % 4 ))
          if [ $PADDING -gt 0 ]; then
            PAYLOAD="${PAYLOAD}$(printf '=%.0s' $(seq 1 $PADDING))"
          fi
          # Decode the payload
          PAYLOAD=$(echo "${PAYLOAD}" | base64 --decode)
          if [ $? -ne 0 ]; then
            echo "Failed to decode base64url payload"
            exit 1
          fi
          SUB_CLAIM=$(echo "${PAYLOAD}" | jq -r '.sub')
          echo "The 'sub' claim is: ${SUB_CLAIM}"
        shell: bash

      - name: CodeGuru Security 
        uses: aws-actions/codeguru-security@v1
        with:
          source_path: .
          aws_region: eu-north-1
          fail_on_severity: Critical

      - name: Print Findings
        run: |
          ls -l
          cat codeguru-security-results.sarif.json

      - name: Upload Result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeguru-security-results.sarif.json
